version: '3.1'

services:
  app:
    image: gmedai/dev_backend
    container_name: gMedAI-backend
    build: .
    ports:
      - 8402:8402
    tty: true
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASS=thangcho
      - DB_NAME=gmedai
      - DB_PORT=5432
      - DB_TYPE=postgres
    command: make run-server
    networks:
      - postgres-network
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: gMedai-postgres
    restart: no
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    networks:
      - postgres-network
    hostname: database
    environment:
      POSTGRES_PASSWORD: thangcho
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

networks:
  postgres-network:
    driver: bridge
    name: postgres-network

volumes:
  pgdata:
    name: pgdata
